processar(1,
3,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/14/parte-primeira-das-causas-primarias/capitulo-i-de-deus/deus-e-o-infinito");
processar(4,
9,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/48/parte-primeira-das-causas-primarias/capitulo-i-de-deus/provas-da-existencia-de-deus");
processar(10,
13,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/55/parte-primeira-das-causas-primarias/capitulo-i-de-deus/atributos-da-divindade");
processar(14,
16,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/60/parte-primeira-das-causas-primarias/capitulo-i-de-deus/panteismo");
processar(17,
20,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/96/parte-primeira-das-causas-primarias/capitulo-ii-dos-elementos-gerais-do-universo/conhecimento-do-principio-das-coisas");
processar(21,
28,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/97/parte-primeira-das-causas-primarias/capitulo-ii-dos-elementos-gerais-do-universo/espirito-e-materia");
processar(29,
34,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/98/parte-primeira-das-causas-primarias/capitulo-ii-dos-elementos-gerais-do-universo/propriedades-da-materia");
processar(35,
36,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/99/parte-primeira-das-causas-primarias/capitulo-ii-dos-elementos-gerais-do-universo/espaco-universal");
processar(37,
42,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/100/parte-primeira-das-causas-primarias/capitulo-iii-da-criacao/formacao-dos-mundos");
processar(43,
49,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/101/parte-primeira-das-causas-primarias/capitulo-iii-da-criacao/formacao-dos-seres-vivos");
processar(50,
51,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/102/parte-primeira-das-causas-primarias/capitulo-iii-da-criacao/povoamento-da-terra-adao");
processar(52,
54,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/103/parte-primeira-das-causas-primarias/capitulo-iii-da-criacao/diversidade-das-racas-humanas");
processar(55,
58,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/104/parte-primeira-das-causas-primarias/capitulo-iii-da-criacao/pluralidade-dos-mundos");
processar(59,
59,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/105/parte-primeira-das-causas-primarias/capitulo-iii-da-criacao/consideracoes-e-concordancias-biblicas-concernentes-a-criacao");
processar(60,
67,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/106/parte-primeira-das-causas-primarias/capitulo-iv-do-principio-vital/seres-organicos-e-inorganicos");
processar(68,
70,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/107/parte-primeira-das-causas-primarias/capitulo-iv-do-principio-vital/a-vida-e-a-morte");
processar(71,
75,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/108/parte-primeira-das-causas-primarias/capitulo-iv-do-principio-vital/inteligencia-e-instinto");
processar(76,
83,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/109/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/origem-e-natureza-dos-espiritos");
processar(84,
87,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/110/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/mundo-normal-primitivo");
processar(88,
92,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/111/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/forma-e-ubiquidade-dos-espiritos");
processar(93,
95,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/112/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/perispirito");
processar(96,
99,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/113/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/diferentes-ordens-de-espiritos");
processar(100,
100,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/361/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/100-observacoes-preliminares");
processar(101,
101,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/362/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/terceira-ordem-espiritos-imperfeitos/101-caracteristicas-gerais");
processar(102,
102,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/363/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/terceira-ordem-espiritos-imperfeitos/102-decima-classe-espiritos-impuros");
processar(103,
103,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/364/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/terceira-ordem-espiritos-imperfeitos/103-nona-classe-espiritos-levianos");
processar(104,
104,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/365/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/terceira-ordem-espiritos-imperfeitos/104-oitava-classe-espiritos-pseudo-sabios");
processar(105,
105,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/366/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/terceira-ordem-espiritos-imperfeitos/105-setima-classe-espiritos-neutros");
processar(106,
106,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/367/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/terceira-ordem-espiritos-imperfeitos/106-sexta-classe-espiritos-batedores-e-perturbadores");
processar(107,
107,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/368/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/segunda-ordem-espiritos-bons/107-caracteristicas-gerais");
processar(108,
108,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/369/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/segunda-ordem-espiritos-bons/108-quinta-classe-espiritos-benevolos");
processar(109,
109,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/370/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/segunda-ordem-espiritos-bons/109-quarta-classe-espiritos-de-ciencia");
processar(110,
110,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/371/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/segunda-ordem-espiritos-bons/110-terceira-classe-espiritos-de-sabedoria");
processar(111,
111,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/372/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/segunda-ordem-espiritos-bons/111-segunda-classe-espiritos-superiores");
processar(112,
112,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/373/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/primeira-ordem-espiritos-puros/112-caracteristicas-gerais");
processar(113,
113,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/374/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/escala-espirita/primeira-ordem-espiritos-puros/113-primeira-classe-classe-unica");
processar(114,
127,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/118/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/progressao-dos-espiritos");
processar(128,
131,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/119/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-i-dos-espiritos/anjos-e-demonios");
processar(132,
133,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/120/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ii-da-encarnacao-dos-espiritos/objetivo-da-encarnacao");
processar(134,
146,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/121/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ii-da-encarnacao-dos-espiritos/a-alma");
processar(147,
148,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/122/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ii-da-encarnacao-dos-espiritos/materialismo");
processar(149,
153,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/123/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iii-da-volta-do-espirito-extinta-a-vida-corporea-a-vida-espiritual/a-alma-apos-a-morte-sua-individualidade-vida-eterna");
processar(154,
162,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/124/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iii-da-volta-do-espirito-extinta-a-vida-corporea-a-vida-espiritual/separacao-da-alma-e-do-corpo");
processar(163,
165,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/125/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iii-da-volta-do-espirito-extinta-a-vida-corporea-a-vida-espiritual/perturbacao-que-se-segue-a-morte");
processar(166,
170,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/126/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iv-da-pluralidade-das-existencias/a-reencarnacao");
processar(171,
171,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/127/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iv-da-pluralidade-das-existencias/justica-da-reencarnacao");
processar(172,
188,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/128/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iv-da-pluralidade-das-existencias/encarnacao-nos-diferentes-mundos");
processar(189,
196,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/129/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iv-da-pluralidade-das-existencias/transmigracoes-progressivas");
processar(197,
199,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/130/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iv-da-pluralidade-das-existencias/sorte-das-criancas-depois-da-morte");
processar(200,
202,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/131/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iv-da-pluralidade-das-existencias/sexo-nos-espiritos");
processar(203,
206,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/132/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iv-da-pluralidade-das-existencias/parentesco-filiacao");
processar(207,
217,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/133/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iv-da-pluralidade-das-existencias/semelhancas-fisicas-e-morais");
processar(218,
221,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/134/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-iv-da-pluralidade-das-existencias/ideias-inatas");
processar(222,
222,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/72/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-v-consideracoes-sobre-a-pluralidade-das-existencias");
processar(223,
233,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/135/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vi-da-vida-espirita/espiritos-errantes");
processar(234,
236,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/136/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vi-da-vida-espirita/mundos-transitorios");
processar(237,
256,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/137/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vi-da-vida-espirita/percepcoes-sensacoes-e-sofrimentos-dos-espiritos");
processar(257,
257,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/138/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vi-da-vida-espirita/ensaio-teorico-da-sensacao-dos-espiritos");
processar(258,
273,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/139/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vi-da-vida-espirita/escolha-de-provas");
processar(274,
290,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/140/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vi-da-vida-espirita/as-relacoes-no-alem-tumulo");
processar(291,
303,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/141/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vi-da-vida-espirita/relacoes-de-simpatia-e-de-antipatia-entre-os-espiritos-metades-eternas");
processar(304,
319,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/142/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vi-da-vida-espirita/recordacao-da-existencia-corporea");
processar(320,
329,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/143/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vi-da-vida-espirita/comemoracao-dos-mortos-funerais");
processar(330,
343,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/144/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vii-da-volta-do-espirito-a-vida-corporal/preludio-da-volta");
processar(344,
360,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/145/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vii-da-volta-do-espirito-a-vida-corporal/uniao-da-alma-e-do-corpo-aborto");
processar(361,
366,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/146/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vii-da-volta-do-espirito-a-vida-corporal/faculdades-morais-e-intelectuais-do-homem");
processar(367,
370,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/147/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vii-da-volta-do-espirito-a-vida-corporal/influencia-do-organismo");
processar(371,
378,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/148/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vii-da-volta-do-espirito-a-vida-corporal/idiotismo-loucura");
processar(379,
385,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/149/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vii-da-volta-do-espirito-a-vida-corporal/a-infancia");


