processar(667,
668,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/184/parte-terceira-das-leis-morais/capitulo-ii-1-lei-de-adoracao/politeismo");
processar(669,
673,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/185/parte-terceira-das-leis-morais/capitulo-ii-1-lei-de-adoracao/sacrificios");
processar(674,
681,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/186/parte-terceira-das-leis-morais/capitulo-iii-2-lei-do-trabalho/necessidade-do-trabalho");
processar(682,
685,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/187/parte-terceira-das-leis-morais/capitulo-iii-2-lei-do-trabalho/limite-do-trabalho-repouso");
processar(686,
687,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/188/parte-terceira-das-leis-morais/capitulo-iv-3-lei-de-reproducao/populacao-do-globo");
processar(688,
692,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/189/parte-terceira-das-leis-morais/capitulo-iv-3-lei-de-reproducao/sucessao-e-aperfeicoamento-das-racas");
processar(693,
694,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/190/parte-terceira-das-leis-morais/capitulo-iv-3-lei-de-reproducao/obstaculos-a-reproducao");
processar(695,
699,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/191/parte-terceira-das-leis-morais/capitulo-iv-3-lei-de-reproducao/casamento-e-celibato");
processar(700,
701,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/192/parte-terceira-das-leis-morais/capitulo-iv-3-lei-de-reproducao/poligamia");
processar(702,
703,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/193/parte-terceira-das-leis-morais/capitulo-v-4-lei-de-conservacao/instinto-de-conservacao");
processar(704,
710,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/194/parte-terceira-das-leis-morais/capitulo-v-4-lei-de-conservacao/meios-de-conservacao");
processar(711,
714,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/195/parte-terceira-das-leis-morais/capitulo-v-4-lei-de-conservacao/gozo-dos-bens-terrenos");
processar(715,
717,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/196/parte-terceira-das-leis-morais/capitulo-v-4-lei-de-conservacao/o-necessario-e-o-superfluo");
processar(718,
727,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/197/parte-terceira-das-leis-morais/capitulo-v-4-lei-de-conservacao/privacoes-voluntarias-mortificacoes");
processar(728,
736,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/198/parte-terceira-das-leis-morais/capitulo-vi-5-lei-de-destruicao/destruicao-necessaria-e-destruicao-abusiva");
processar(737,
741,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/199/parte-terceira-das-leis-morais/capitulo-vi-5-lei-de-destruicao/flagelos-destruidores");
processar(742,
745,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/200/parte-terceira-das-leis-morais/capitulo-vi-5-lei-de-destruicao/guerras");
processar(746,
751,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/201/parte-terceira-das-leis-morais/capitulo-vi-5-lei-de-destruicao/assassinio");
processar(752,
756,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/202/parte-terceira-das-leis-morais/capitulo-vi-5-lei-de-destruicao/crueldade");
processar(757,
759,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/203/parte-terceira-das-leis-morais/capitulo-vi-5-lei-de-destruicao/duelo");
processar(760,
765,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/204/parte-terceira-das-leis-morais/capitulo-vi-5-lei-de-destruicao/pena-de-morte");
processar(766,
768,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/205/parte-terceira-das-leis-morais/capitulo-vii-6-lei-de-sociedade/necessidade-da-vida-social");
processar(769,
772,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/206/parte-terceira-das-leis-morais/capitulo-vii-6-lei-de-sociedade/vida-de-insulamento-voto-de-silencio");
processar(773,
775,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/207/parte-terceira-das-leis-morais/capitulo-vii-6-lei-de-sociedade/lacos-de-familia");
processar(776,
778,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/208/parte-terceira-das-leis-morais/capitulo-viii-7-lei-do-progresso/estado-da-natureza");
processar(779,
785,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/209/parte-terceira-das-leis-morais/capitulo-viii-7-lei-do-progresso/marcha-do-progresso");
processar(786,
789,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/210/parte-terceira-das-leis-morais/capitulo-viii-7-lei-do-progresso/povos-degenerados");
processar(790,
793,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/211/parte-terceira-das-leis-morais/capitulo-viii-7-lei-do-progresso/civilizacao");
processar(794,
797,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/212/parte-terceira-das-leis-morais/capitulo-viii-7-lei-do-progresso/progresso-da-legislacao-humana");
processar(798,
802,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/213/parte-terceira-das-leis-morais/capitulo-viii-7-lei-do-progresso/influencia-do-espiritismo-no-progresso");
