processar(803,
803,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/214/parte-terceira-das-leis-morais/capitulo-ix-8-lei-de-igualdade/igualdade-natural");
processar(804,
805,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/215/parte-terceira-das-leis-morais/capitulo-ix-8-lei-de-igualdade/desigualdade-das-aptidoes");
processar(806,
807,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/216/parte-terceira-das-leis-morais/capitulo-ix-8-lei-de-igualdade/desigualdades-sociais");
processar(808,
813,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/217/parte-terceira-das-leis-morais/capitulo-ix-8-lei-de-igualdade/desigualdade-das-riquezas");
processar(814,
816,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/218/parte-terceira-das-leis-morais/capitulo-ix-8-lei-de-igualdade/as-provas-da-riqueza-e-da-miseria");
processar(817,
822,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/219/parte-terceira-das-leis-morais/capitulo-ix-8-lei-de-igualdade/igualdade-dos-direitos-do-homem-e-da-mulher");
processar(823,
824,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/220/parte-terceira-das-leis-morais/capitulo-ix-8-lei-de-igualdade/igualdade-perante-o-tumulo");
processar(825,
828,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/221/parte-terceira-das-leis-morais/capitulo-x-9-lei-de-liberdade/liberdade-natural");
processar(829,
832,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/222/parte-terceira-das-leis-morais/capitulo-x-9-lei-de-liberdade/escravidao");
processar(833,
834,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/223/parte-terceira-das-leis-morais/capitulo-x-9-lei-de-liberdade/liberdade-de-pensar");
processar(835,
842,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/224/parte-terceira-das-leis-morais/capitulo-x-9-lei-de-liberdade/liberdade-de-consciencia");
processar(843,
850,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/225/parte-terceira-das-leis-morais/capitulo-x-9-lei-de-liberdade/livre-arbitrio");
processar(851,
867,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/226/parte-terceira-das-leis-morais/capitulo-x-9-lei-de-liberdade/fatalidade");
processar(868,
871,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/227/parte-terceira-das-leis-morais/capitulo-x-9-lei-de-liberdade/conhecimento-do-futuro");
processar(872,
872,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/228/parte-terceira-das-leis-morais/capitulo-x-9-lei-de-liberdade/resumo-teorico-do-movel-das-acoes-humanas");
processar(873,
879,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/229/parte-terceira-das-leis-morais/capitulo-xi-10-lei-de-justica-de-amor-e-de-caridade/justica-e-direito-natural");
processar(880,
885,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/230/parte-terceira-das-leis-morais/capitulo-xi-10-lei-de-justica-de-amor-e-de-caridade/direito-de-propriedade-roubo");
processar(886,
889,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/231/parte-terceira-das-leis-morais/capitulo-xi-10-lei-de-justica-de-amor-e-de-caridade/caridade-e-amor-do-proximo");
processar(890,
892,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/232/parte-terceira-das-leis-morais/capitulo-xi-10-lei-de-justica-de-amor-e-de-caridade/amor-materno-e-filial");
processar(893,
906,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/233/parte-terceira-das-leis-morais/capitulo-xii-da-perfeicao-moral/as-virtudes-e-os-vicios");
processar(907,
912,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/234/parte-terceira-das-leis-morais/capitulo-xii-da-perfeicao-moral/as-paixoes");
processar(913,
917,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/235/parte-terceira-das-leis-morais/capitulo-xii-da-perfeicao-moral/o-egoismo");
processar(918,
918,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/236/parte-terceira-das-leis-morais/capitulo-xii-da-perfeicao-moral/caracteres-do-homem-de-bem");
processar(919,
919,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/237/parte-terceira-das-leis-morais/capitulo-xii-da-perfeicao-moral/conhecimento-de-si-mesmo");
processar(920,
933,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/238/parte-quarta-das-esperancas-e-consolacoes/capitulo-i-das-penas-e-gozos-terrestres/felicidade-e-infelicidade-relativas");
processar(934,
936,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/239/parte-quarta-das-esperancas-e-consolacoes/capitulo-i-das-penas-e-gozos-terrestres/perda-dos-entes-queridos");
processar(937,
938,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/240/parte-quarta-das-esperancas-e-consolacoes/capitulo-i-das-penas-e-gozos-terrestres/decepcoes-ingratidao-afeicoes-destruidas");
processar(939,
940,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/241/parte-quarta-das-esperancas-e-consolacoes/capitulo-i-das-penas-e-gozos-terrestres/unioes-antipaticas");
processar(941,
942,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/242/parte-quarta-das-esperancas-e-consolacoes/capitulo-i-das-penas-e-gozos-terrestres/temor-da-morte");
processar(943,
957,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/243/parte-quarta-das-esperancas-e-consolacoes/capitulo-i-das-penas-e-gozos-terrestres/desgosto-da-vida-suicidio");
processar(958,
959,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/244/parte-quarta-das-esperancas-e-consolacoes/capitulo-ii-das-penas-e-gozos-futuros/o-nada-vida-futura");
processar(960,
962,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/245/parte-quarta-das-esperancas-e-consolacoes/capitulo-ii-das-penas-e-gozos-futuros/intuicao-das-penas-e-gozos-futuros");
processar(963,
964,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/246/parte-quarta-das-esperancas-e-consolacoes/capitulo-ii-das-penas-e-gozos-futuros/intervencao-de-deus-nas-penas-e-recompensas");
processar(965,
982,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/247/parte-quarta-das-esperancas-e-consolacoes/capitulo-ii-das-penas-e-gozos-futuros/natureza-das-penas-e-gozos-futuros");
processar(983,
989,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/248/parte-quarta-das-esperancas-e-consolacoes/capitulo-ii-das-penas-e-gozos-futuros/penas-temporais");
processar(990,
1002,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/249/parte-quarta-das-esperancas-e-consolacoes/capitulo-ii-das-penas-e-gozos-futuros/expiacao-e-arrependimento");
processar(1003,
1009,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/250/parte-quarta-das-esperancas-e-consolacoes/capitulo-ii-das-penas-e-gozos-futuros/duracao-das-penas-futuras");
processar(1010,
1010,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/251/parte-quarta-das-esperancas-e-consolacoes/capitulo-ii-das-penas-e-gozos-futuros/ressurreicao-da-carne");
processar(1012,
1019,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/252/parte-quarta-das-esperancas-e-consolacoes/capitulo-ii-das-penas-e-gozos-futuros/paraiso-inferno-e-purgatorio-paraiso-perdido-pecado-original");
