processarLE(386,
391,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/150/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vii-da-volta-do-espirito-a-vida-corporal/simpatias-e-antipatias-terrenas");
processarLE(392,
399,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/151/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-vii-da-volta-do-espirito-a-vida-corporal/esquecimento-do-passado");
processarLE(400,
412,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/152/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-viii-da-emancipacao-da-alma/o-sono-e-os-sonhos");
processarLE(413,
418,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/731/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-viii-da-emancipacao-da-alma/visitas-espiritas-entre-pessoas-vivas/413");
processarLE(419,
421,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/154/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-viii-da-emancipacao-da-alma/transmissao-oculta-do-pensamento");
processarLE(422,
424,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/155/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-viii-da-emancipacao-da-alma/letargia-catalepsia-mortes-aparentes");
processarLE(425,
438,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/156/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-viii-da-emancipacao-da-alma/sonambulismo");
processarLE(439,
446,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/157/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-viii-da-emancipacao-da-alma/extase");
processarLE(447,
454,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/158/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-viii-da-emancipacao-da-alma/segunda-vista");
processarLE(455,
455,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/159/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-viii-da-emancipacao-da-alma/resumo-teorico-do-sonambulismo-do-extase-e-da-segunda-vista");
processarLE(456,
458,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/160/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/faculdade-que-tem-os-espiritos-de-penetrar-os-nossos-pensamentos");
processarLE(459,
472,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/161/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/influencia-oculta-dos-espiritos-em-nossos-pensamentos-e-atos");
processarLE(473,
480,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/162/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/possessos");
processarLE(481,
483,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/163/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/convulsionarios");
processarLE(484,
488,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/164/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/afeicao-que-os-espiritos-votam-a-certas-pessoas");
processarLE(489,
521,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/165/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/anjos-guardiaes-espiritos-protetores-familiares-ou-simpaticos");
processarLE(522,
524,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/166/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/pressentimentos");
processarLE(525,
535,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/167/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/influencia-dos-espiritos-nos-acontecimentos-da-vida");
processarLE(536,
540,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/168/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/acao-dos-espiritos-sobre-os-fenomenos-da-natureza");
processarLE(541,
548,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/169/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/os-espiritos-durante-os-combates");
processarLE(549,
550,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/170/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/pactos");
processarLE(551,
556,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/171/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/poder-oculto-talismas-feiticeiros");
processarLE(557,
557,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/172/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-ix-da-intervencao-dos-espiritos-no-mundo-corporal/bencaos-e-maldicoes");
processarLE(558,
584,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/77/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-x-das-ocupacoes-e-missoes-dos-espiritos");
processarLE(585,
591,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/173/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-xi-dos-tres-reinos/os-minerais-e-as-plantas");
processarLE(592,
610,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/174/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-xi-dos-tres-reinos/os-animais-e-o-homem");
processarLE(611,
613,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/175/parte-segunda-do-mundo-espirita-ou-mundo-dos-espiritos/capitulo-xi-dos-tres-reinos/metempsicose");
processarLE(614,
618,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/176/parte-terceira-das-leis-morais/capitulo-i-da-lei-divina-ou-natural/caracteres-da-lei-natural");
processarLE(619,
628,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/177/parte-terceira-das-leis-morais/capitulo-i-da-lei-divina-ou-natural/conhecimento-da-lei-natural");
processarLE(629,
646,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/178/parte-terceira-das-leis-morais/capitulo-i-da-lei-divina-ou-natural/o-bem-e-o-mal");
processarLE(647,
648,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/179/parte-terceira-das-leis-morais/capitulo-i-da-lei-divina-ou-natural/divisao-da-lei-natural");
processarLE(649,
652,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/180/parte-terceira-das-leis-morais/capitulo-ii-1-lei-de-adoracao/objetivo-da-adoracao");
processarLE(653,
656,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/181/parte-terceira-das-leis-morais/capitulo-ii-1-lei-de-adoracao/adoracao-exterior");
processarLE(657,
657,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/182/parte-terceira-das-leis-morais/capitulo-ii-1-lei-de-adoracao/vida-contemplativa");
processarLE(658,
666,
"https://kardecpedia.com/roteiro-de-estudos/2/o-livro-dos-espiritos/183/parte-terceira-das-leis-morais/capitulo-ii-1-lei-de-adoracao/a-prece");
